### ISSUE TITLE
AbortController not working

### ISSUE THREAD

**Issue by nmocruz** [elbywan/wretch#126] opened 2022-03-02 19:05 UTC
I have an api client not working and seems that it was working long time ago. not sure if was webpack breaking it or what.
some speudocode
```
class api{
  let controller = null;
  async callMultipletimesUseOnlyLastClicked (a){
      if(this.controller)
           this.controller.abort();
      this.controller = new AbortController();
      let data = await apibase.url('xx').signal(this.controller)
               .get()
               .json()
      controller = null;
      return data;
  }
}
```
the request can take 2 or 4 sec and to discard the previous requests I'm aborting any controller.
before I was able to abort requests but now I have bug here and It seems like a new factory is created and loosing the reference to the controller.

**Comment by elbywan** [comment] 2022-03-03 08:56
Hey @nmocruz,

> before I was able to abort requests but now I have bug here and It seems like a new factory is created and loosing the reference to the controller.

I'm not sure your issue is related to wretch, I tried reproducing with the code you provided but it seems to be working as expected:

```js
class Api {
  constructor() {
    this.apibase = wretch("https://jsonplaceholder.typicode.com")
  }

  async getPosts () {
    if(this.controller) {
      this.controller.abort();
      console.log("aborted")
    }
    this.controller = new AbortController();
    let data = await this.apibase.url('/posts/1')
      .signal(this.controller)
      .get()
      .json()
    this.controller = null;
    return data;
  }
}

const api = new Api()

api.getPosts().then(data => console.log("First request", data)).catch(console.error)
api.getPosts().then(data => console.log("Second request", data)).catch(console.error)
```

<img width="1792" alt="Capture d’écran 2022-03-03 à 09 55 52" src="https://user-images.githubusercontent.com/3428394/156530776-72faf4d3-659b-467f-8a17-49f8bf72c1c7.png">

**Comment by nmocruz** [comment] 2022-03-03 09:39
not sure if this is due the way that webpack babel or ts-loader is importing the library because it was working before and stopped after migrating a few libraries like webpack, typescript etc.

**Comment by elbywan** [comment] 2022-03-04 13:06
> I did a bit of debugging and seems like is called selfFactory a few times and the last is losing the reference to the controller. I can be wrong because my webpack source maps are not perfect.

Hmm this is weird, `selfFactory` preserves fetch options (signal is an option) unless specified otherwise explicitely by calling `.options(…, true)`. 

I don't think that this issue is related to `wretch` itself so I'm going to close it. Feel free to reopen if you can provide a reproducible sample.

**Closed by elbywan** 2022-03-04 13:06 UTC
Labels: question
